server:
  port: 8080
  servlet:
    context-path: /data-manager

spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/dspmt
    username: root
    password: 111111
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.xuyifan.dspmanager.bean
