package com.xuyifan.dspmanager.bean;

public class Menu {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.ID
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.NAME
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.URL
     *
     * @mbggenerated
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.PARENT_ID
     *
     * @mbggenerated
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.SYSTEM
     *
     * @mbggenerated
     */
    private String system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column menu.IS_PARENT
     *
     * @mbggenerated
     */
    private Integer isParent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.ID
     *
     * @return the value of menu.ID
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.ID
     *
     * @param id the value for menu.ID
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.NAME
     *
     * @return the value of menu.NAME
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.NAME
     *
     * @param name the value for menu.NAME
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.URL
     *
     * @return the value of menu.URL
     *
     * @mbggenerated
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.URL
     *
     * @param url the value for menu.URL
     *
     * @mbggenerated
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.PARENT_ID
     *
     * @return the value of menu.PARENT_ID
     *
     * @mbggenerated
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.PARENT_ID
     *
     * @param parentId the value for menu.PARENT_ID
     *
     * @mbggenerated
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.SYSTEM
     *
     * @return the value of menu.SYSTEM
     *
     * @mbggenerated
     */
    public String getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.SYSTEM
     *
     * @param system the value for menu.SYSTEM
     *
     * @mbggenerated
     */
    public void setSystem(String system) {
        this.system = system == null ? null : system.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column menu.IS_PARENT
     *
     * @return the value of menu.IS_PARENT
     *
     * @mbggenerated
     */
    public Integer getIsParent() {
        return isParent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column menu.IS_PARENT
     *
     * @param isParent the value for menu.IS_PARENT
     *
     * @mbggenerated
     */
    public void setIsParent(Integer isParent) {
        this.isParent = isParent;
    }
}